// Generated by apps/android/scripts/generate.mjs. Do not edit. Source: GRADIENT_PRESET_STOPS in @trackbit/types.
package com.trackbit.core.model

/** Each preset theme's heatmap gradient. [ColorTheme.Custom]'s is the default for a new custom gradient. */
val GradientPresets: Map<ColorTheme, List<ColorStop>> = mapOf(
    ColorTheme.Green to listOf(
        ColorStop(0f, Rgba(241f, 245f, 249f, 0.1f)),
        ColorStop(0.4f, Rgba(134f, 239f, 172f, 0.4f)),
        ColorStop(1f, Rgba(21f, 128f, 61f, 1f)),
    ),
    ColorTheme.Blue to listOf(
        ColorStop(0f, Rgba(241f, 245f, 249f, 0.1f)),
        ColorStop(0.4f, Rgba(147f, 197f, 253f, 0.4f)),
        ColorStop(1f, Rgba(29f, 78f, 216f, 1f)),
    ),
    ColorTheme.Orange to listOf(
        ColorStop(0f, Rgba(241f, 245f, 249f, 0.1f)),
        ColorStop(0.4f, Rgba(253f, 186f, 116f, 0.4f)),
        ColorStop(1f, Rgba(194f, 65f, 12f, 1f)),
    ),
    ColorTheme.Purple to listOf(
        ColorStop(0f, Rgba(241f, 245f, 249f, 0.1f)),
        ColorStop(0.4f, Rgba(216f, 180f, 254f, 0.4f)),
        ColorStop(1f, Rgba(126f, 34f, 206f, 1f)),
    ),
    ColorTheme.Rose to listOf(
        ColorStop(0f, Rgba(241f, 245f, 249f, 0.1f)),
        ColorStop(0.4f, Rgba(253f, 164f, 175f, 0.4f)),
        ColorStop(1f, Rgba(190f, 18f, 60f, 1f)),
    ),
    ColorTheme.Fire to listOf(
        ColorStop(0f, Rgba(255f, 237f, 213f, 0.1f)),
        ColorStop(0.5f, Rgba(249f, 115f, 22f, 0.5f)),
        ColorStop(1f, Rgba(185f, 28f, 28f, 1f)),
    ),
    ColorTheme.Custom to listOf(
        ColorStop(0f, Rgba(255f, 0f, 0f, 1f)),
        ColorStop(0.5f, Rgba(255f, 225f, 0f, 1f)),
        ColorStop(1f, Rgba(12f, 148f, 62f, 1f)),
    ),
)
