// Generated by apps/android/scripts/generate.mjs. Do not edit. Source: apps/frontend/src/index.css.
package com.trackbit.core.designsystem.theme

import androidx.compose.ui.graphics.Color

/** The web app's shadcn tokens, converted from oklch to sRGB. [TrackbitTheme] maps them onto Material 3 roles. */
internal data class WebPalette(
    val background: Color,
    val foreground: Color,
    val card: Color,
    val cardForeground: Color,
    val popover: Color,
    val popoverForeground: Color,
    val primary: Color,
    val primaryForeground: Color,
    val secondary: Color,
    val secondaryForeground: Color,
    val muted: Color,
    val mutedForeground: Color,
    val accent: Color,
    val accentForeground: Color,
    val destructive: Color,
    val border: Color,
    val input: Color,
    val ring: Color,
    val chart1: Color,
    val chart2: Color,
    val chart3: Color,
    val chart4: Color,
    val chart5: Color,
    val sidebar: Color,
    val sidebarForeground: Color,
    val sidebarPrimary: Color,
    val sidebarPrimaryForeground: Color,
    val sidebarAccent: Color,
    val sidebarAccentForeground: Color,
    val sidebarBorder: Color,
    val sidebarRing: Color,
)

internal val WebLight = WebPalette(
    background = Color(0xFFFFFFFF), // oklch(1 0 0)
    foreground = Color(0xFF0A0A0A), // oklch(0.145 0 0)
    card = Color(0xFFFFFFFF), // oklch(1 0 0)
    cardForeground = Color(0xFF0A0A0A), // oklch(0.145 0 0)
    popover = Color(0xFFFFFFFF), // oklch(1 0 0)
    popoverForeground = Color(0xFF0A0A0A), // oklch(0.145 0 0)
    primary = Color(0xFF171717), // oklch(0.205 0 0)
    primaryForeground = Color(0xFFFAFAFA), // oklch(0.985 0 0)
    secondary = Color(0xFFF5F5F5), // oklch(0.97 0 0)
    secondaryForeground = Color(0xFF171717), // oklch(0.205 0 0)
    muted = Color(0xFFF5F5F5), // oklch(0.97 0 0)
    mutedForeground = Color(0xFF737373), // oklch(0.556 0 0)
    accent = Color(0xFFF5F5F5), // oklch(0.97 0 0)
    accentForeground = Color(0xFF171717), // oklch(0.205 0 0)
    destructive = Color(0xFFE7000B), // oklch(0.577 0.245 27.325)
    border = Color(0xFFE5E5E5), // oklch(0.922 0 0)
    input = Color(0xFFE5E5E5), // oklch(0.922 0 0)
    ring = Color(0xFFA1A1A1), // oklch(0.708 0 0)
    chart1 = Color(0xFFF54900), // oklch(0.646 0.222 41.116)
    chart2 = Color(0xFF009689), // oklch(0.6 0.118 184.704)
    chart3 = Color(0xFF104E64), // oklch(0.398 0.07 227.392)
    chart4 = Color(0xFFFFB900), // oklch(0.828 0.189 84.429)
    chart5 = Color(0xFFFE9A00), // oklch(0.769 0.188 70.08)
    sidebar = Color(0xFFFAFAFA), // oklch(0.985 0 0)
    sidebarForeground = Color(0xFF0A0A0A), // oklch(0.145 0 0)
    sidebarPrimary = Color(0xFF171717), // oklch(0.205 0 0)
    sidebarPrimaryForeground = Color(0xFFFAFAFA), // oklch(0.985 0 0)
    sidebarAccent = Color(0xFFF5F5F5), // oklch(0.97 0 0)
    sidebarAccentForeground = Color(0xFF171717), // oklch(0.205 0 0)
    sidebarBorder = Color(0xFFE5E5E5), // oklch(0.922 0 0)
    sidebarRing = Color(0xFFA1A1A1), // oklch(0.708 0 0)
)

internal val WebDark = WebPalette(
    background = Color(0xFF0A0A0A), // oklch(0.145 0 0)
    foreground = Color(0xFFFAFAFA), // oklch(0.985 0 0)
    card = Color(0xFF171717), // oklch(0.205 0 0)
    cardForeground = Color(0xFFFAFAFA), // oklch(0.985 0 0)
    popover = Color(0xFF171717), // oklch(0.205 0 0)
    popoverForeground = Color(0xFFFAFAFA), // oklch(0.985 0 0)
    primary = Color(0xFFE5E5E5), // oklch(0.922 0 0)
    primaryForeground = Color(0xFF171717), // oklch(0.205 0 0)
    secondary = Color(0xFF262626), // oklch(0.269 0 0)
    secondaryForeground = Color(0xFFFAFAFA), // oklch(0.985 0 0)
    muted = Color(0xFF262626), // oklch(0.269 0 0)
    mutedForeground = Color(0xFFA1A1A1), // oklch(0.708 0 0)
    accent = Color(0xFF262626), // oklch(0.269 0 0)
    accentForeground = Color(0xFFFAFAFA), // oklch(0.985 0 0)
    destructive = Color(0xFFFF6467), // oklch(0.704 0.191 22.216)
    border = Color(0x1AFFFFFF), // oklch(1 0 0 / 10%)
    input = Color(0x26FFFFFF), // oklch(1 0 0 / 15%)
    ring = Color(0xFF737373), // oklch(0.556 0 0)
    chart1 = Color(0xFF1447E6), // oklch(0.488 0.243 264.376)
    chart2 = Color(0xFF00BC7D), // oklch(0.696 0.17 162.48)
    chart3 = Color(0xFFFE9A00), // oklch(0.769 0.188 70.08)
    chart4 = Color(0xFFAD46FF), // oklch(0.627 0.265 303.9)
    chart5 = Color(0xFFFF2056), // oklch(0.645 0.246 16.439)
    sidebar = Color(0xFF171717), // oklch(0.205 0 0)
    sidebarForeground = Color(0xFFFAFAFA), // oklch(0.985 0 0)
    sidebarPrimary = Color(0xFF1447E6), // oklch(0.488 0.243 264.376)
    sidebarPrimaryForeground = Color(0xFFFAFAFA), // oklch(0.985 0 0)
    sidebarAccent = Color(0xFF262626), // oklch(0.269 0 0)
    sidebarAccentForeground = Color(0xFFFAFAFA), // oklch(0.985 0 0)
    sidebarBorder = Color(0x1AFFFFFF), // oklch(1 0 0 / 10%)
    sidebarRing = Color(0xFF737373), // oklch(0.556 0 0)
)
