#!/usr/bin/env node
// Generates the Android resources that mirror the web app, so neither side is copied by hand:
//
//   strings   apps/frontend/src/i18n/locales/{en,es}/*.json  → core/i18n  values[-es]/strings.xml, xml/locales_config.xml
//   presets   @trackbit/types GRADIENT_PRESET_STOPS           → core/model GradientPresets.kt
//   colors    apps/frontend/src/index.css (:root, .dark)      → core/designsystem WebColors.kt
//   icons     HABIT_ICON_IDS + the web's lucide registry      → core/designsystem drawable/ic_habit_*.xml
//             UI_ICONS (the lucide icons the web's screens use) → core/designsystem drawable/ic_ui_*.xml
//
// It also fails when the handwritten HabitIcon / ColorTheme enums no longer match @trackbit/types.
//
// Usage (from the repo root, after `pnpm install` and `pnpm --filter @trackbit/types build`):
//   node apps/android/scripts/generate.mjs           write the outputs
//   node apps/android/scripts/generate.mjs --check   exit 1 if any output is stale (CI)

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ANDROID = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const REPO = resolve(ANDROID, '../..');
const FRONTEND = join(REPO, 'apps/frontend');
const LOCALES_DIR = join(FRONTEND, 'src/i18n/locales');
const DEFAULT_LOCALE = 'en';
const GENERATED_BY = 'Generated by apps/android/scripts/generate.mjs. Do not edit.';

const DESIGNSYSTEM = join(ANDROID, 'core/designsystem/src/main');
const MODEL_SRC = join(ANDROID, 'core/model/src/main/kotlin/com/trackbit/core/model');
const DRAWABLE_DIR = join(DESIGNSYSTEM, 'res/drawable');
const ICON_PREFIX = 'ic_habit_';
const UI_ICON_PREFIX = 'ic_ui_';

/** Icons the app's screens use, by drawable suffix → lucide-react component, as on the web. */
const UI_ICONS = {
    activity: 'Activity',
    arrow_left: 'ArrowLeft',
    bar_chart: 'BarChart3',
    bar_chart_2: 'BarChart2',
    calendar_days: 'CalendarDays',
    calendar_search: 'CalendarSearch',
    check: 'Check',
    circle_check: 'CheckCircle2',
    chevron_down: 'ChevronDown',
    chevron_left: 'ChevronLeft',
    chevron_right: 'ChevronRight',
    clock: 'Clock',
    dumbbell: 'Dumbbell',
    flame: 'Flame',
    grip_vertical: 'GripVertical',
    hash: 'Hash',
    layers: 'Layers',
    list: 'List',
    lock: 'Lock',
    log_out: 'LogOut',
    map_pin: 'MapPin',
    minus: 'Minus',
    more_vertical: 'EllipsisVertical',
    pencil: 'Pencil',
    pause: 'Pause',
    play: 'Play',
    plus: 'Plus',
    scale: 'Scale',
    search: 'Search',
    settings: 'Settings',
    shield_alert: 'ShieldAlert',
    stop: 'Square',
    timer: 'Timer',
    trash: 'Trash2',
    trending_up: 'TrendingUp',
    trophy: 'Trophy',
    user: 'User',
};

class GenerateError extends Error {}
const fail = (message) => {
    throw new GenerateError(message);
};

// ---------------------------------------------------------------------------------------------
// Strings: ICU messages → Android string resources
// ---------------------------------------------------------------------------------------------

/** `tracker` + `list.items_count` → `tracker_list_items_count`. */
function resourceName(namespace, key) {
    const name = `${namespace}_${key}`.replace(/[.-]/g, '_');
    if (!/^[a-z][a-z0-9_]*$/.test(name)) fail(`"${namespace}:${key}" doesn't make a valid resource name (${name})`);
    return name;
}

/**
 * Splits an ICU message into text and `{…}` parts, honouring nested braces. ICU's `''` is a
 * literal apostrophe; a lone `'` is literal too (i18next-icu's default apostrophe mode).
 */
function tokenize(message) {
    const parts = [];
    let text = '';
    for (let i = 0; i < message.length; i++) {
        const ch = message[i];
        if (ch === "'" && message[i + 1] === "'") {
            text += "'";
            i++;
        } else if (ch === '{') {
            let depth = 1;
            let j = i + 1;
            for (; j < message.length && depth > 0; j++) {
                if (message[j] === '{') depth++;
                if (message[j] === '}') depth--;
            }
            if (depth > 0) fail(`Unbalanced braces in "${message}"`);
            if (text) parts.push({ text });
            text = '';
            parts.push({ arg: message.slice(i + 1, j - 1) });
            i = j - 1;
        } else {
            text += ch;
        }
    }
    if (text) parts.push({ text });
    return parts;
}

/** Android string-resource escaping for literal text. `%` is doubled only in format strings. */
function escapeText(text, formatted) {
    let out = text
        .replace(/\\/g, '\\\\')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/'/g, "\\'")
        .replace(/"/g, '\\"')
        .replace(/\n/g, '\\n');
    if (formatted) out = out.replace(/%/g, '%%');
    return out;
}

const escapeLeading = (s) => (/^[@?]/.test(s) ? `\\${s}` : s);

const PLURAL_QUANTITIES = new Set(['zero', 'one', 'two', 'few', 'many', 'other']);

/** Parses `count, plural, one {…} other {…}` into its variable and branches. */
function parsePlural(arg) {
    const match = /^\s*(\w+)\s*,\s*plural\s*,(.*)$/s.exec(arg);
    if (!match) return null;
    const [, variable, body] = match;
    const branches = {};
    let selector;
    for (const part of tokenize(body)) {
        if (part.text !== undefined) {
            for (const quantity of part.text.trim().split(/\s+/).filter(Boolean)) {
                if (!PLURAL_QUANTITIES.has(quantity)) fail(`Plural selector "${quantity}" has no Android equivalent in {${arg}}`);
                selector = quantity;
            }
        } else {
            if (!selector) fail(`Plural branch without a selector in {${arg}}`);
            branches[selector] = part.arg;
            selector = undefined;
        }
    }
    if (!branches.other) fail(`Plural {${arg}} needs an "other" branch`);
    return { variable, branches };
}

/**
 * Converts one ICU message. Arguments become positional `%N$s` in order of first appearance;
 * `#` inside a plural becomes the count as `%N$d`.
 */
function convertMessage(message, where) {
    const parts = tokenize(message);
    const plurals = parts.filter((p) => p.arg !== undefined && parsePlural(p.arg));
    if (plurals.length > 1) fail(`${where}: more than one plural in a message`);
    if (plurals.length === 1 && parts.length > 1) fail(`${where}: a plural must be the whole message`);

    const order = [];
    const index = (name) => {
        if (!/^\w+$/.test(name)) fail(`${where}: unsupported ICU argument {${name}}`);
        if (!order.includes(name)) order.push(name);
        return order.indexOf(name) + 1;
    };

    const render = (tokens, formatted, countVariable) =>
        tokens
            .map((p) => {
                if (p.text !== undefined) {
                    if (countVariable === undefined) return escapeText(p.text, formatted);
                    return p.text
                        .split('#')
                        .map((t) => escapeText(t, formatted))
                        .join(`%${index(countVariable)}$d`);
                }
                return `%${index(p.arg.trim())}$s`;
            })
            .join('');

    if (plurals.length === 1) {
        const { variable, branches } = parsePlural(plurals[0].arg);
        index(variable);
        const items = Object.fromEntries(
            Object.entries(branches).map(([q, body]) => [q, escapeLeading(render(tokenize(body), true, variable))]),
        );
        return { plural: items };
    }
    const formatted = parts.some((p) => p.arg !== undefined);
    return { text: escapeLeading(render(parts, formatted)), formatted };
}

function readLocale(locale) {
    const dir = join(LOCALES_DIR, locale);
    const entries = [];
    for (const file of readdirSync(dir).filter((f) => f.endsWith('.json')).sort()) {
        const namespace = file.replace(/\.json$/, '');
        const bundle = JSON.parse(readFileSync(join(dir, file), 'utf8'));
        for (const [key, value] of Object.entries(bundle)) {
            if (typeof value !== 'string') fail(`${locale}/${file}: "${key}" is not a string (nested keys aren't supported)`);
            entries.push({ name: resourceName(namespace, key), value, where: `${locale}/${file} "${key}"` });
        }
    }
    const seen = new Set();
    for (const { name, where } of entries) {
        if (seen.has(name)) fail(`${where} collides with another key as ${name}`);
        seen.add(name);
    }
    return entries;
}

function stringsXml(entries) {
    const lines = entries.map(({ name, value, where }) => {
        const converted = convertMessage(value, where);
        if (converted.plural) {
            const items = Object.entries(converted.plural).map(([q, t]) => `        <item quantity="${q}">${t}</item>`);
            return [`    <plurals name="${name}">`, ...items, '    </plurals>'].join('\n');
        }
        const notFormatted = !converted.formatted && converted.text.includes('%') ? ' formatted="false"' : '';
        return `    <string name="${name}"${notFormatted}>${converted.text}</string>`;
    });
    return [
        '<?xml version="1.0" encoding="utf-8"?>',
        `<!-- ${GENERATED_BY} Source: apps/frontend/src/i18n/locales. -->`,
        // The web's copy is the source of truth, so its typography stays as it is, and features
        // pick strings from this catalogue over time.
        '<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="UnusedResources,TypographyEllipsis">',
        ...lines,
        '</resources>',
        '',
    ].join('\n');
}

function generateStrings() {
    const locales = readdirSync(LOCALES_DIR).filter((d) => existsSync(join(LOCALES_DIR, d, 'common.json'))).sort();
    const reference = new Set(readLocale(DEFAULT_LOCALE).map((e) => e.name));
    const outputs = {};
    for (const locale of locales) {
        const entries = readLocale(locale);
        const names = new Set(entries.map((e) => e.name));
        const missing = [...reference].filter((n) => !names.has(n));
        const extra = [...names].filter((n) => !reference.has(n));
        if (missing.length || extra.length) {
            fail(`Locale "${locale}" doesn't match "${DEFAULT_LOCALE}": missing [${missing}], extra [${extra}]`);
        }
        const dir = locale === DEFAULT_LOCALE ? 'values' : `values-${locale}`;
        outputs[join(ANDROID, 'core/i18n/src/main/res', dir, 'strings.xml')] = stringsXml(entries);
    }
    outputs[join(ANDROID, 'core/i18n/src/main/res/xml/locales_config.xml')] = localeConfigXml(locales);
    return outputs;
}

/** The languages the system's per-app language setting offers: those the strings ship in. */
function localeConfigXml(locales) {
    return [
        '<?xml version="1.0" encoding="utf-8"?>',
        `<!-- ${GENERATED_BY} Source: apps/frontend/src/i18n/locales. -->`,
        '<locale-config xmlns:android="http://schemas.android.com/apk/res/android">',
        ...locales.map((locale) => `    <locale android:name="${locale}" />`),
        '</locale-config>',
        '',
    ].join('\n');
}

// ---------------------------------------------------------------------------------------------
// @trackbit/types: gradient presets, and a drift check of the handwritten enums
// ---------------------------------------------------------------------------------------------

async function loadTypes() {
    const dist = join(REPO, 'packages/types/dist/index.js');
    if (!existsSync(dist)) fail('packages/types/dist is missing: run `pnpm --filter @trackbit/types build` first');
    return import(pathToFileURL(dist).href);
}

const pascal = (id) => id.replace(/(^|[-_])(\w)/g, (_, __, c) => c.toUpperCase());
const kotlinFloat = (n) => `${n}f`;

function generatePresets(types) {
    const entries = types.COLOR_THEMES.map((theme) => {
        const stops = types.GRADIENT_PRESET_STOPS[theme].map(({ position, color }) => {
            const channels = color.map(kotlinFloat).join(', ');
            return `        ColorStop(${kotlinFloat(position)}, Rgba(${channels})),`;
        });
        return [`    ColorTheme.${pascal(theme)} to listOf(`, ...stops, '    ),'].join('\n');
    });
    const source = [
        `// ${GENERATED_BY} Source: GRADIENT_PRESET_STOPS in @trackbit/types.`,
        'package com.trackbit.core.model',
        '',
        '/** Each preset theme\'s heatmap gradient. [ColorTheme.Custom]\'s is the default for a new custom gradient. */',
        'val GradientPresets: Map<ColorTheme, List<ColorStop>> = mapOf(',
        ...entries,
        ')',
        '',
    ].join('\n');
    return { [join(MODEL_SRC, 'GradientPresets.kt')]: source };
}

/** The wire strings of a handwritten `enum class <name>` in core:model's Enums.kt. */
function enumWires(name) {
    const source = readFileSync(join(MODEL_SRC, 'Enums.kt'), 'utf8');
    const body = new RegExp(`enum class ${name}\\b[^{]*\\{([\\s\\S]*?);`).exec(source)?.[1];
    if (!body) fail(`enum class ${name} not found in Enums.kt`);
    return [...body.matchAll(/\w+\("([^"]+)"\)/g)].map((m) => m[1]);
}

function checkEnums(types) {
    for (const [name, expected] of [['HabitIcon', types.HABIT_ICON_IDS], ['ColorTheme', types.COLOR_THEMES]]) {
        const actual = enumWires(name);
        const missing = expected.filter((v) => !actual.includes(v));
        const extra = actual.filter((v) => !expected.includes(v));
        if (missing.length || extra.length) {
            fail(`core:model ${name} doesn't match @trackbit/types: missing [${missing}], extra [${extra}]`);
        }
    }
}

// ---------------------------------------------------------------------------------------------
// Colors: the web's oklch tokens → sRGB
// ---------------------------------------------------------------------------------------------

/** oklch(L C H [/ A]) → [r, g, b, a], sRGB channels 0–255 clipped to the gamut. */
function oklchToRgba(value) {
    const m = /^oklch\(\s*([\d.]+)(%?)\s+([\d.]+)\s+([\d.]+)\s*(?:\/\s*([\d.]+)(%?))?\s*\)$/.exec(value);
    if (!m) fail(`Unsupported color "${value}"`);
    const l = Number(m[1]) / (m[2] ? 100 : 1);
    const c = Number(m[3]);
    const h = (Number(m[4]) * Math.PI) / 180;
    const alpha = m[5] === undefined ? 1 : Number(m[5]) / (m[6] ? 100 : 1);

    const a = c * Math.cos(h);
    const b = c * Math.sin(h);
    const l_ = (l + 0.3963377774 * a + 0.2158037573 * b) ** 3;
    const m_ = (l - 0.1055613458 * a - 0.0638541728 * b) ** 3;
    const s_ = (l - 0.0894841775 * a - 1.291485548 * b) ** 3;
    const linear = [
        4.0767416621 * l_ - 3.3077115913 * m_ + 0.2309699292 * s_,
        -1.2684380046 * l_ + 2.6097574011 * m_ - 0.3413193965 * s_,
        -0.0041960863 * l_ - 0.7034186147 * m_ + 1.707614701 * s_,
    ];
    const gamma = (x) => (x <= 0.0031308 ? 12.92 * x : 1.055 * x ** (1 / 2.4) - 0.055);
    const rgb = linear.map((x) => Math.round(Math.min(1, Math.max(0, gamma(x))) * 255));
    return [...rgb, Math.round(alpha * 255)];
}

function cssTokens(css, selector) {
    const start = css.search(new RegExp(`(^|\\n)${selector.replace('.', '\\.')}\\s*\\{`));
    if (start < 0) fail(`${selector} block not found in index.css`);
    const block = css.slice(start, css.indexOf('}', start));
    return Object.fromEntries([...block.matchAll(/--([\w-]+):\s*(oklch\([^)]*\))/g)].map((m) => [m[1], m[2]]));
}

function generateColors() {
    const css = readFileSync(join(FRONTEND, 'src/index.css'), 'utf8');
    const argb = ([r, g, b, a]) => `0x${[a, r, g, b].map((x) => x.toString(16).padStart(2, '0')).join('').toUpperCase()}`;
    const camel = (token) => token.replace(/-(\w)/g, (_, c) => c.toUpperCase());
    const light = cssTokens(css, ':root');
    const dark = cssTokens(css, '.dark');
    const names = Object.keys(light);
    const mismatch = [...names.filter((t) => !(t in dark)), ...Object.keys(dark).filter((t) => !(t in light))];
    if (mismatch.length) fail(`:root and .dark define different tokens: ${mismatch}`);
    const palette = (name, tokens) => [
        `internal val ${name} = WebPalette(`,
        ...names.map((token) => `    ${camel(token)} = Color(${argb(oklchToRgba(tokens[token]))}), // ${tokens[token]}`),
        ')',
    ];
    const source = [
        `// ${GENERATED_BY} Source: apps/frontend/src/index.css.`,
        'package com.trackbit.core.designsystem.theme',
        '',
        'import androidx.compose.ui.graphics.Color',
        '',
        '/** The web app\'s shadcn tokens, converted from oklch to sRGB. [TrackbitTheme] maps them onto Material 3 roles. */',
        'internal data class WebPalette(',
        ...names.map((token) => `    val ${camel(token)}: Color,`),
        ')',
        '',
        ...palette('WebLight', light),
        '',
        ...palette('WebDark', dark),
        '',
    ].join('\n');
    return { [join(DESIGNSYSTEM, 'kotlin/com/trackbit/core/designsystem/theme/WebColors.kt')]: source };
}

// ---------------------------------------------------------------------------------------------
// Icons: lucide icon nodes → VectorDrawables
// ---------------------------------------------------------------------------------------------

/** `book: { icon: BookOpen, … }` pairs from the web's icon registry. */
function webIconComponents(ids) {
    const source = readFileSync(join(FRONTEND, 'src/features/habits-configuration/habit-icons.ts'), 'utf8');
    const components = Object.fromEntries([...source.matchAll(/(\w+):\s*\{\s*icon:\s*(\w+)/g)].map((m) => [m[1], m[2]]));
    const missing = ids.filter((id) => !components[id]);
    if (missing.length) fail(`habit-icons.ts has no icon for [${missing}]`);
    return components;
}

/** lucide-react component name → the file its icon node lives in (aliases included). */
function lucideFiles(lucideDir) {
    const index = readFileSync(join(lucideDir, 'dist/esm/lucide-react.js'), 'utf8');
    const files = {};
    for (const m of index.matchAll(/export \{([^}]*)\} from '\.\/icons\/([\w-]+)\.js'/g)) {
        for (const alias of m[1].matchAll(/default as (\w+)/g)) files[alias[1]] = m[2];
    }
    return files;
}

const num = (v) => Number(v);
const fmt = (n) => String(Math.round(n * 1000) / 1000);

/** One lucide element as VectorDrawable path data. */
function pathData([tag, attrs]) {
    switch (tag) {
        case 'path':
            return attrs.d;
        case 'circle': {
            const [cx, cy, r] = [attrs.cx, attrs.cy, attrs.r].map(num);
            return `M${fmt(cx - r)},${fmt(cy)}a${fmt(r)},${fmt(r)} 0 1,0 ${fmt(2 * r)},0a${fmt(r)},${fmt(r)} 0 1,0 ${fmt(-2 * r)},0`;
        }
        case 'ellipse': {
            const [cx, cy, rx, ry] = [attrs.cx, attrs.cy, attrs.rx, attrs.ry].map(num);
            return `M${fmt(cx - rx)},${fmt(cy)}a${fmt(rx)},${fmt(ry)} 0 1,0 ${fmt(2 * rx)},0a${fmt(rx)},${fmt(ry)} 0 1,0 ${fmt(-2 * rx)},0`;
        }
        case 'rect': {
            const [x, y, w, h] = [attrs.x ?? 0, attrs.y ?? 0, attrs.width, attrs.height].map(num);
            const rx = Math.min(num(attrs.rx ?? attrs.ry ?? 0), w / 2);
            const ry = Math.min(num(attrs.ry ?? attrs.rx ?? 0), h / 2);
            if (!rx && !ry) return `M${fmt(x)},${fmt(y)}h${fmt(w)}v${fmt(h)}h${fmt(-w)}z`;
            const arc = (dx, dy) => `a${fmt(rx)},${fmt(ry)} 0 0,1 ${fmt(dx)},${fmt(dy)}`;
            return (
                `M${fmt(x + rx)},${fmt(y)}h${fmt(w - 2 * rx)}${arc(rx, ry)}v${fmt(h - 2 * ry)}${arc(-rx, ry)}` +
                `h${fmt(-(w - 2 * rx))}${arc(-rx, -ry)}v${fmt(-(h - 2 * ry))}${arc(rx, -ry)}z`
            );
        }
        case 'line':
            return `M${attrs.x1},${attrs.y1}L${attrs.x2},${attrs.y2}`;
        case 'polyline':
        case 'polygon':
            return `M${attrs.points.trim().replace(/\s+/g, ' ')}${tag === 'polygon' ? 'z' : ''}`;
        default:
            return fail(`Unsupported lucide element <${tag}>`);
    }
}

function vectorXml(node, source) {
    const paths = node.map((element) => [
        '    <path',
        `        android:pathData="${pathData(element)}"`,
        '        android:strokeColor="#FF000000"',
        '        android:strokeWidth="2"',
        '        android:strokeLineCap="round"',
        '        android:strokeLineJoin="round" />',
    ].join('\n'));
    return [
        `<!-- ${GENERATED_BY} Source: lucide ${source} (ISC). Tint it; the stroke is black. -->`,
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="24dp"',
        '    android:height="24dp"',
        '    android:viewportWidth="24"',
        '    android:viewportHeight="24">',
        ...paths,
        '</vector>',
        '',
    ].join('\n');
}

async function generateIcons(types) {
    const lucideDir = join(FRONTEND, 'node_modules/lucide-react');
    if (!existsSync(lucideDir)) fail('apps/frontend/node_modules/lucide-react is missing: run `pnpm install` first');
    const components = webIconComponents(types.HABIT_ICON_IDS);
    const files = lucideFiles(lucideDir);
    const icons = [
        ...types.HABIT_ICON_IDS.map((id) => [`${ICON_PREFIX}${id}`, components[id]]),
        ...Object.entries(UI_ICONS).map(([name, component]) => [`${UI_ICON_PREFIX}${name}`, component]),
    ];
    const outputs = {};
    for (const [drawable, component] of icons) {
        const file = files[component] ?? fail(`lucide-react has no icon named ${component}`);
        const { __iconNode } = await import(pathToFileURL(join(lucideDir, 'dist/esm/icons', `${file}.js`)).href);
        outputs[join(DRAWABLE_DIR, `${drawable}.xml`)] = vectorXml(__iconNode, file);
    }
    return outputs;
}

// ---------------------------------------------------------------------------------------------

async function main() {
    const check = process.argv.includes('--check');
    const types = await loadTypes();
    checkEnums(types);
    const outputs = {
        ...generateStrings(),
        ...generatePresets(types),
        ...generateColors(),
        ...(await generateIcons(types)),
    };

    const stale = existsSync(DRAWABLE_DIR)
        ? readdirSync(DRAWABLE_DIR)
              .filter((f) => f.startsWith(ICON_PREFIX) || f.startsWith(UI_ICON_PREFIX))
              .map((f) => join(DRAWABLE_DIR, f))
              .filter((path) => !(path in outputs))
        : [];
    const changed = Object.entries(outputs).filter(([path, content]) => !existsSync(path) || readFileSync(path, 'utf8') !== content);

    if (check) {
        const problems = [...changed.map(([p]) => `out of date: ${relative(REPO, p)}`), ...stale.map((p) => `stale: ${relative(REPO, p)}`)];
        if (problems.length) {
            console.error(`${problems.join('\n')}\nRun \`pnpm android:generate\` and commit the result.`);
            process.exit(1);
        }
        console.log(`All ${Object.keys(outputs).length} generated files are up to date.`);
        return;
    }
    for (const [path, content] of changed) {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, content);
    }
    for (const path of stale) rmSync(path);
    console.log(`Wrote ${changed.length} of ${Object.keys(outputs).length} files${stale.length ? `, removed ${stale.length}` : ''}.`);
}

main().catch((error) => {
    console.error(error instanceof GenerateError ? `generate: ${error.message}` : error);
    process.exit(1);
});
